Repository oVirt/ovirt-web-ui, pull requests merged in 2018-11, with the labels that each got.

#838 ux-redesign: VM Details > Disks Card
  src/actions/disks.js
  src/actions/index.js
  src/actions/pendingTasks.js
  src/actions/vm.js
  src/components/NewDiskDialog/actions.js
  src/components/NewDiskDialog/constants.js
  src/components/NewDiskDialog/index.js
  src/components/NewDiskDialog/sagas.js
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/components/VmDetails/cards/DisksCard/DiskListItem.js
  src/components/VmDetails/cards/DisksCard/DiskStateIcon.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/DisksCard/style.css
  src/components/VmDetails/itemListStyle.css
  src/components/VmDisks/VmDisk.js
  src/components/VmDisks/actions.js
  src/components/VmDisks/constants.js
  src/components/VmDisks/sagas.js
  src/components/utils.js
  src/constants/index.js
  src/intl/messages.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/ovirtapi/types.js
  src/reducers/pendingTasks.js
  src/reducers/vms.js
  src/saga/disks.js
  src/sagas.js
Labels: enhancement, needs_QE, redesign

#839 Add deep fetch for data refresh
  src/actions/index.js
  src/components/PageRouter.js
  src/components/Pages/index.js
  src/constants/index.js
  src/constants/pages.js
  src/reducers/config.js
  src/routes.js
  src/sagas.js
  src/selectors.js
Labels: enhancement, needs_QE

#798 disable all action buttons when removing snapshot
  src/components/VmDetails/cards/SnapshotsCard/SnapshotItem.js
  src/components/VmDetails/cards/SnapshotsCard/index.js
Labels: needs_QE, status_ON_QA

#813 Change cluster filtering by permits instead of roles
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/ovirtapi/types.js
  src/sagas.js
  src/utils/permissions.js
Labels: enhancement, needs_QE

#860 console: fix the 'in use' check
  src/saga/console/index.js
Labels: bug, needs_QE, severity_low

#858 Fix loading of SSH key in options dialog
  src/components/OptionsDialog/sagas.js
  src/sagas.js
Labels: needs_QE, status_ON_QA

#871 Move the core error messages above PageRouter
  src/App.js
Labels: bug, needs_QE, severity_low, status_ON_QA

#857 Fix bad tooltip breaking in utilization cards
  src/components/VmDetails/cards/UtilizationCard/style.css
Labels: needs_QE, status_ON_QA
