Repository oVirt/ovirt-web-ui, pull requests merged in 2019-12, with the labels that each got.

#987 Create VM Wizard
  package.json
  scripts/start.js
  src/actions/templates.js
  src/actions/vm.js
  src/components/CreateVmWizard/AddVmButton.js
  src/components/CreateVmWizard/CreateVmWizard.js
  src/components/CreateVmWizard/dataPropTypes.js
  src/components/CreateVmWizard/index.js
  src/components/CreateVmWizard/steps/BasicSettings.js
  src/components/CreateVmWizard/steps/Networking.js
  src/components/CreateVmWizard/steps/Storage.js
  src/components/CreateVmWizard/steps/SummaryReview.js
  src/components/CreateVmWizard/steps/style.css
  src/components/Grid/GridComponents.js
  src/components/PageRouter.js
  src/components/Pages/index.js
  src/components/Toolbar/VmsListToolbar.js
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/NicsCard/NicEditor.js
  src/components/VmDetails/cards/NicsCard/index.js
  src/components/VmDialog/AddVmButton.js
  src/components/VmDialog/index.js
  src/components/utils/build-select-box-lists.js
  src/components/utils/index.js
  src/components/utils/suggest-names.js
  src/constants/index.js
  src/helpers.js
  src/helpers.test.js
  src/intl/messages.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/ovirtapi/types.js
  src/reducers/templates.js
  src/reducers/utils.test.js
  src/reducers/vms.js
  src/routes.js
  src/sagas/disks.js
  src/sagas/index.js
  src/sagas/login.js
  src/sagas/templates.js
  src/sagas/vmChanges.js
  src/utils/index.js
  src/utils/permissions.js
  src/utils/round.js
  src/utils/storage-conversion.js
  src/utils/type-validation.js
  src/utils/unit-conversion.js
  src/utils/unit-conversion.test.js
  yarn.lock
Labels: Flag: Needs QE, Flag: Needs UI review

#1144 Refresh scheduler delay <= 0 disables background refresh
  src/sagas/index.js
Labels: Type: Developers only

#1143 Fix regression in GlobalErrorBoundary
  src/GlobalErrorBoundary.js
  src/index.js
Labels: Type: Developers only

#1092 Full-Screen console
  src/components/CounterAlert.js
  src/components/VmConsole/index.js
  src/components/VmConsole/style.css
  src/components/sharedStyle.css
  src/intl/messages.js
  src/react-console/VncActions.js
  src/react-console/index.js
Labels: Flag: Needs UI review, Status: ON_QA
