Repository oVirt/ovirt-web-ui, pull requests merged in 2019-07, with the labels that each got.

#1004 Added sysprep to Details card for windows VM
  src/components/VmDetails/cards/DetailsCard/CloudInit/CloudInitForm.js
  src/components/VmDetails/cards/DetailsCard/CloudInit/SysprepForm.js
  src/components/VmDetails/cards/DetailsCard/CloudInit/index.js
  src/components/VmDetails/cards/DetailsCard/CloudInit/timezones.json
  src/components/VmDetails/cards/DetailsCard/FieldRow.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/intl/messages.js
  src/ovirtapi/transform.js
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#1047 updated jquery, patternfly, patternfly-react, handlebars and html-loader
  package.json
  yarn.lock
Labels: Flag: Bugzilla, Status: ON_QA

#1050 Remove logger.js in favor of straight console logging
  src/components/VmDialog/index.js
  src/index.js
  src/logger.js
  src/optionsManager.js
  src/ovirtapi/index.js
  src/ovirtapi/transport.js
  src/reducers/utils.js
  src/reducers/vms.js
  src/sagas/console/index.js
  src/sagas/console/vvFileUtils.js
  src/sagas/index.js
  src/sagas/login.js
  src/sagas/utils.js
  src/storage.js
Labels: Type: Developers only

#1011 Fixed checkbox size in Remove VM confirmation dialog
  src/components/Checkbox/index.js
  src/components/Checkbox/style.css
  src/components/VmActions/index.js
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#1044 Default memory unit to MiB while editing VM memory on details card
  src/components/VmDetails/cards/DetailsCard/index.js
Labels: Flag: Needs QE, Status: ON_QA

#1056 Only show file system chart when there is >0 file systems
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
Labels: Flag: Needs QE, Status: ON_QA

#1061 Allow starting dev server without opening browser
  DEVELOPERS.md
  scripts/start.js
Labels: Type: Developers only

#1062 Removed payload from actions
  src/actions/clusters.js
  src/actions/hosts.js
  src/actions/index.js
  src/actions/operatingSystems.js
  src/actions/pendingTasks.js
  src/actions/pool.js
  src/actions/storageDomains.js
  src/actions/templates.js
  src/actions/userMessages.js
  src/actions/vnicProfiles.js
  src/components/OptionsDialog/actions.js
  src/sagas/storageDomains.js
  src/sagas/utils.js
Labels: Flag: Doesn't need QE, Type: Developers only, Type: Enhancement

#1052 Fixed showing of manual pool VMs
  src/components/VmsList/Vms.js
  src/reducers/vms.js
  src/sagas/index.js
Labels: Status: ON_QA
