Repository oVirt/ovirt-web-ui, pull requests merged in 2019-02, with the labels that each got.

#947 Verify translated message formats match English message formats
  package.json
  scripts/intl/normalize-messages.js
  src/intl/index.test.js
  src/intl/messages.test.js
  src/intl/translated-messages.json
  yarn.lock
Labels: Flag: Doesn't need QE, Type: Developers only

#941 Fix 'cow' and 'raw' disk bug
  src/actions/vm.js
  src/components/VmDialog/index.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
Labels: Flag: Needs QE, Status: ON_QA

#934 Fixed utilization card responsiveness bug
  src/components/VmDetails/cards/UtilizationCard/index.js
  src/components/VmDetails/cards/UtilizationCard/style.css
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#929 Fix everytime showed console SSO modal and update modal message
  src/actions/console.js
  src/components/VmActions/ConsoleConfirmationModal.js
  src/intl/messages.js
  src/saga/console/index.js
  src/utils/index.js
Labels: Flag: Needs QE, Status: ON_QA

#953 Externalize strings in Utilization and Snapshots Cards
  package.json
  scripts/intl/dummy-locale.js
  src/components/VmDetails/cards/SnapshotsCard/NewSnapshotModal.js
  src/components/VmDetails/cards/SnapshotsCard/index.js
  src/components/VmDetails/cards/UtilizationCard/CpuCharts.js
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/cards/UtilizationCard/MemoryCharts.js
  src/components/VmDetails/cards/UtilizationCard/NetworkingCharts.js
  src/components/VmDetails/cards/UtilizationCard/NoHistoricData.js
  src/components/VmDetails/cards/UtilizationCard/NoLiveData.js
  src/components/VmDetails/cards/UtilizationCard/index.js
  src/components/VmDetails/index.js
  src/intl/messages.js
Labels: Flag: Doesn't need QE, Flag: Doesn't need UI review

#919 Added permissions to disk card
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/components/VmDetails/cards/DisksCard/DiskListItem.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/saga/storageDomains.js
  src/saga/utils.js
  src/sagas.js
  src/utils/permissions.js
Labels: Flag: Needs QE, Status: ON_QA

#925 adjust handling of src/version.js.in so src/version.js can be dropped
  .gitignore
  .travis.yml
  DEVELOPERS.md
  config/paths.js
  ovirt-web-ui.spec.in
  package.json
  scripts/build.js
  scripts/pretest.js
  scripts/utils/checkRequiredFiles.js
  src/version.js
Labels: Flag: Doesn't need QE, Type: Developers only

#917 Added name validation and cloud-init update to overview card
  src/components/VmDetails/BaseCard.js
  src/components/VmDetails/cards/OverviewCard/index.js
  src/components/VmDetails/cards/OverviewCard/style.css
  src/components/utils.js
  src/components/utils.test.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#952 Allow users without edit VM permissions to change a running VM's CD
  src/actions/vm.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/sagas.js
  src/utils/array-utils.js
  src/utils/array-utils.test.js
  src/utils/index.js
  src/utils/permissions.js
Labels: Flag: Bugzilla, Flag: Needs QE, Flag: Needs UI review, Status: ON_QA
