Repository oVirt/ovirt-web-ui, pull requests merged in 2019-09, with the labels that each got.

#1098 Tooltip and OverlayTrigger component
  src/components/OverlayTooltip/index.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DisksCard/DiskListItem.js
  src/components/VmDetails/cards/DisksCard/DiskStateIcon.js
  src/components/VmDetails/cards/NicsCard/NicLinkStateIcon.js
  src/components/VmDetails/cards/NicsCard/NicListItem.js
  src/components/VmDetails/cards/SnapshotsCard/SnapshotItem.js
Labels: Flag: Doesn't need QE, Flag: Doesn't need UI review

#1063 Refactor App init code (redux store create and config) and OS icon caching
  src/actions/index.js
  src/components/VmsList/BaseCard.js
  src/constants/index.js
  src/helpers.js
  src/index.js
  src/sagas/index.js
  src/sagas/login.js
  src/sagas/osIcons.js
  src/storage.js
  src/store.js
Labels: Type: Developers only

#1017 Fixed saving NIC with empty VNIC Profile
  src/components/VmDetails/cards/NicsCard/NicEditor.js
  src/components/VmNics/NewNicModal.js
  src/ovirtapi/transform.js
Labels: Flag: Needs UI review, Status: ON_QA

#1048 Replaced PF3 charts with PF4
  ovirt-web-ui.spec.in
  package.json
  src/components/VmDetails/cards/UtilizationCard/CpuCharts.js
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/cards/UtilizationCard/MemoryCharts.js
  src/components/VmDetails/cards/UtilizationCard/NetworkingCharts.js
  src/components/VmDetails/cards/UtilizationCard/UtilizationCharts/AreaChart.js
  src/components/VmDetails/cards/UtilizationCard/UtilizationCharts/BarChart.js
  src/components/VmDetails/cards/UtilizationCard/UtilizationCharts/DonutChart.js
  src/components/VmDetails/cards/UtilizationCard/style.css
  src/components/VmDetails/cards/UtilizationCard/tooltip-helper.js
  src/intl/messages.js
  yarn.lock
Labels: Status: ON_QA

#1115 Update build to use yarn from ovirt-engine-nodejs-modules
  DEVELOPERS.md
  Makefile.am
  automation/build.packages.force
  automation/build.repos
  automation/build.sh
  configure.ac
  ovirt-web-ui.spec.in
Labels: Type: Developers only

#1114 Allow use of alternate branding by the DEV server
  DEVELOPERS.md
  config/paths.js
  config/webpack.config.dev.js
  scripts/start.js
Labels: Type: Developers only

#1116 Update autogen/automake configurations and yarn integration
  .travis.yml
  Makefile.am
  package.json
Labels: Type: Developers only

#1120 Only run autogen.sh on yarn install if it is available
  package.json
Labels: Type: Developers only

#1033 Make snapshot popover and Disks edit modal more responsive
  src/components/VmDetails/cards/DisksCard/style.css
  src/components/VmDetails/cards/SnapshotsCard/SnapshotItem.js
  src/components/VmDetails/cards/SnapshotsCard/style.css
Labels: Flag: Needs QE, Status: ON_QA

#1086 Hover texts in masthead fixed and changed
  src/components/VmUserMessages/index.js
  src/components/VmsPageHeader/UserMenu.js
  src/components/VmsPageHeader/index.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#1068 make overview card more responsive. removed use of Media
  src/components/VmDetails/cards/OverviewCard/index.js
  src/components/VmDetails/cards/OverviewCard/style.css
Labels: Flag: Needs QE, Status: ON_QA

#1082 Hide host info from non-admin users
  src/components/VmDetails/cards/DetailsCard/index.js
Labels: Flag: Needs QE, Status: ON_QA

#1028 responsive - VM Details, set minimum card widths
  src/components/VmDetails/index.js
  src/components/VmDetails/style.css
Labels: Flag: Needs QE, Status: ON_QA
