Repository oVirt/ovirt-web-ui, pull requests merged in 2019-06, with the labels that each got.

#956 Added NoVNC console page
  config/paths.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  package.json
  src/actions/console.js
  src/actions/index.js
  src/components/Loader.js
  src/components/PageRouter.js
  src/components/Pages/index.js
  src/components/Toolbar/Toolbar.js
  src/components/Toolbar/index.js
  src/components/Toolbar/style.css
  src/components/VmActions/Action.js
  src/components/VmActions/ConfirmationModal.js
  src/components/VmActions/ConsoleConfirmationModal.js
  src/components/VmActions/index.js
  src/components/VmActions/style.css
  src/components/VmConsole/VmConsoleInstructionsModal.js
  src/components/VmConsole/VmConsoleSelector.js
  src/components/VmConsole/images/disconnect_icon.png
  src/components/VmConsole/images/download_icon.png
  src/components/VmConsole/index.js
  src/components/VmConsole/style.css
  src/components/VmDetails/cards/DetailsCard/ConsoleList.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DetailsCard/style.css
  src/components/VmsList/Vms.js
  src/components/VmsList/style.css
  src/components/sharedStyle.css
  src/components/utils.js
  src/constants/console.js
  src/constants/index.js
  src/constants/pages.js
  src/index-nomodules.css
  src/intl/messages.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/react-console/VncActions.js
  src/react-console/constants.js
  src/react-console/index.js
  src/reducers/config.js
  src/reducers/consoles.js
  src/reducers/vms.js
  src/routes.js
  src/sagas/console/index.js
  src/sagas/index.js
  src/sagas/login.js
  yarn.lock
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#1010 Set minimum ovirt-engine REST API to version 4.2
  src/version.js.in
Labels: Type: Developers only

#1036 import patternfly-react CSS for runtime use
  src/index.js
Labels: Type: Developers only

#1016 Fixed textarea resize bug
  src/index-nomodules.css
Labels: Flag: Needs QE, Flag: Needs UI review

#1038 Refactor components/utils.js
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/cards/UtilizationCard/MemoryCharts.js
  src/components/VmDetails/cards/UtilizationCard/tooltip-helper.js
  src/components/utils.js
  src/components/utils/cpu-topology.js
  src/components/utils/cpu-topology.test.js
  src/components/utils/index.js
  src/components/utils/utils.js
  src/components/utils/validation.js
  src/components/utils/validation.test.js
  src/components/utils/vm-icons.js
  src/utils/index.js
Labels: Type: Developers only

#1018 Added validation for Disk name
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/components/utils/validation.js
  src/intl/messages.js
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#1037 Refactor `GridComponents` to enable use outside `VmDetails`
  src/components/Grid/GridComponents.js
  src/components/Grid/index.js
  src/components/Grid/style.css
  src/components/VmDetails/GridComponents.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/NicsCard/NicListItem.js
  src/components/VmDetails/cards/NicsCard/index.js
  src/components/VmDetails/cards/UtilizationCard/index.js
  src/components/VmDetails/index.js
  src/components/VmDetails/style.css
Labels: Type: Developers only

#1019 Added template filtering for VM create dialog
  src/components/VmDialog/index.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/sagas/index.js
  src/sagas/utils.js
  src/utils/permissions.js
Labels: Flag: Needs QE, Status: ON_QA
