Repository oVirt/ovirt-web-ui, pull requests merged in 2019-08, with the labels that each got.

#1064 Update vulnerable dependency versions, refactor React Context use
  ovirt-web-ui.spec.in
  package.json
  src/components/VmsList/BaseCard.js
  yarn.lock
Labels: Flag: Needs QE, Status: ON_QA

#986 Added fetching events from engine
  src/actions/userMessages.js
  src/components/VmUserMessages/index.js
  src/components/VmUserMessages/style.css
  src/constants/index.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/ovirtapi/types.js
  src/reducers/userMessages.js
  src/sagas/index.js
  src/sagas/login.js
Labels: Status: ON_QA

#997 Added Filters and Sort fields
  src/actions/vm.js
  src/components/PageRouter.js
  src/components/Toolbar/Toolbar.js
  src/components/Toolbar/VmFilters.js
  src/components/Toolbar/VmSort.js
  src/components/Toolbar/VmsListToolbar.js
  src/components/Toolbar/index.js
  src/components/Toolbar/style.css
  src/components/VmActions/index.js
  src/components/VmActions/style.css
  src/components/VmsList/Vms.js
  src/constants/index.js
  src/intl/messages.js
  src/ovirtapi/transform.js
  src/reducers/vms.js
  src/routes.js
  src/sagas/index.js
  src/sagas/login.js
  src/utils/index.js
  src/utils/vms-filters.js
  src/utils/vms-sort.js
Labels: Status: ON_QA

#1079 Disabled delete button on disks and NICs is gray enough
  src/components/VmDetails/cards/SnapshotsCard/style.css
  src/components/VmDetails/itemListStyle.css
  src/intl/messages.js
Labels: Flag: Needs UI review, Status: ON_QA

#1027 Text wrapping in Utilization card
  src/components/VmDetails/cards/UtilizationCard/style.css
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA
