Repository oVirt/ovirt-web-ui, pull requests merged in 2019-11, with the labels that each got.

#1117 Refactored log out
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  ovirt-web-ui.spec.in
  package.json
  scripts/start.js
  src/App.js
  src/GlobalErrorBoundary.js
  src/components/Header.js
  src/components/NoLogin/images/sign-out.svg
  src/components/NoLogin/index.js
  src/components/NoLogin/style.css
  src/components/VmsPageHeader/index.js
  src/index.js
  src/intl/messages.js
  src/sagas/index.js
  yarn.lock
Labels: Status: ON_QA

#1131 Fix action menu render error and console error on VmsList page
  src/components/VmActions/index.js
  src/components/VmsList/BaseCard.js
  src/components/VmsList/style.css
Labels: Status: ON_QA

#1104 Disk Edit Dialog - Add Tooltip
  src/components/OverlayTooltip/index.js
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#1111 User messages refactor
  src/actions/userMessages.js
  src/components/ToastNotifications.js
  src/reducers/userMessages.js
  src/sagas/index.js
Labels: Status: ON_QA

#1138 update STDCI, add distros fc30 and el8
  automation.yaml
  automation/build.packages.force
  automation/build.repos
  automation/build.sh
  ovirt-web-ui.spec.in
Labels: Type: Developers only

#1084 About Dialog - Report issues URL added to branding
  branding/fixed-strings.json
  src/GlobalErrorBoundary.js
  src/components/About.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#1110 Start and Shutdown VM Notification
  src/components/ToastNotifications.js
  src/intl/messages.js
  src/sagas/index.js
Labels: Flag: Needs QE, Status: ON_QA

#1137 Card list, running VM actions default to open VM's console
  src/components/VmActions/index.js
Labels: Flag: Needs QE, Status: ON_QA
