Repository oVirt/ovirt-web-ui, pull requests merged in 2019-01, with the labels that each got.

#890 Fix visual artifacts in NICs and Disks cards
  src/components/VmDetails/BaseCard.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/NicsCard/index.js
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/style.css
Labels: needs_QE, status_ON_QA

#867 Added advanced options to VM Details Card
  src/components/SelectBox.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/sharedStyle.css
  src/helpers.js
  src/intl/messages.js
  src/selectors.js
Labels: Status: ON_QA

#876 Add support for ISOs in any storage domain
  src/actions/storageDomains.js
  src/actions/vm.js
  src/components/VmDialog/index.js
  src/components/VmsPageHeader/index.js
  src/constants/index.js
  src/ovirtapi/index.js
  src/ovirtapi/transform.js
  src/reducers/storageDomains.js
  src/saga/login.js
  src/saga/storageDomains.js
  src/saga/utils.js
  src/sagas.js
Labels: Flag: Bugzilla, Flag: Needs QE, Severity: Medium, Status: ON_QA

#897 Remove status from Details card, add uptime to Overview
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DetailsCard/style.css
  src/components/VmDetails/cards/OverviewCard/index.js
  src/components/VmDetails/cards/OverviewCard/style.css
  src/ovirtapi/transform.js
  src/ovirtapi/types.js
  src/utils/format.js
Labels: Flag: Needs QE, Status: ON_QA

#886 (backport to 1.4) Add additional IE11 support to load the App, Edge support to download console.vv files
  .gitignore
  Makefile.am
  config/paths.js
  config/polyfills.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  index.html
  index.jsp
  index.jsp.template
  ovirt-web-ui.spec.in
  package.json
  scripts/start.js
  src/helpers.js
  static/index.hbs
  yarn.lock
Labels: Flag: Needs QE, Status: ON_QA

#904 Added unsupported browser component
  src/App.js
  src/index-nomodules.css
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#873 ux-redesign: Redesign utilization disk card
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/cards/UtilizationCard/NoLiveData.js
  src/components/VmDetails/cards/UtilizationCard/index.js
  src/components/VmDetails/cards/UtilizationCard/style.css
  src/ovirtapi/transform.js
  src/ovirtapi/types.js
Labels: Flag: Needs QE, Status: ON_QA

#914 Fix disk and memory chart units
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/cards/UtilizationCard/MemoryCharts.js
  src/helpers.js
  src/utils/round.js
Labels: Status: ON_QA

#935 Fix pencil edit button tooltip
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/NicsCard/index.js
  src/components/VmDetails/cards/OverviewCard/index.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA
