Repository oVirt/ovirt-web-ui, pull requests merged in 2019-10, with the labels that each got.

#1029 NICS card text wrapping
  src/components/Grid/GridComponents.js
  src/components/VmDetails/cards/NicsCard/NicListItem.js
  src/components/VmDetails/cards/NicsCard/style.css
  src/components/VmDetails/itemListStyle.css
Labels: Flag: Needs QE, Status: ON_QA

#1026 VM Details card - Add ellipse/tooltip for IP Addresses
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DetailsCard/style.css
Labels: Flag: Needs QE, Status: ON_QA

#1067 Add kebob actions menu and changed Shutdown button type to default in Dashboard
  src/components/VmActions/Action.js
  src/components/VmActions/index.js
  src/components/VmActions/style.css
  src/index-nomodules.css
Labels: Flag: Needs QE, Status: ON_QA

#990 Pool redesign
  src/components/Pages/index.js
  src/components/Toolbar/index.js
  src/components/VmActions/ConfirmationModal.js
  src/components/VmActions/index.js
  src/components/VmDetail/LastMessage.js
  src/components/VmDetail/VmConsoles.js
  src/components/VmDetail/VmStatus.js
  src/components/VmDetail/index.js
  src/components/VmDetail/labels.js
  src/components/VmDetail/style.css
  src/components/VmDetails/BaseCard.js
  src/components/VmDetails/CardEditButton.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/OverviewCard/index.js
  src/components/VmDetails/cards/OverviewCard/style.css
  src/components/VmDetails/cards/SnapshotsCard/SnapshotDetail.js
  src/components/VmDetails/cards/SnapshotsCard/SnapshotItem.js
  src/components/VmsList/BaseCard.js
  src/components/VmsList/Pool.js
  src/components/VmsList/Vm.js
  src/components/VmsList/Vms.js
  src/components/VmsList/style.css
  src/constants/pages.js
  src/intl/messages.js
  src/ovirtapi/transform.js
  src/routes.js
  src/sagas/index.js
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#1087 UserSessionTimeOut automatic logout fixed
  src/App.js
Labels: Flag: Needs QE, Status: ON_QA

#1099 About Dialog - Add link to documentation
  branding/fixed-strings.json
  src/components/About.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#1083 Tooltips on the edit button use the same patternfly-react style
  src/components/OverlayTooltip/index.js
  src/components/VmDetails/CardEditButton.js
Labels: Flag: Needs QE, Status: ON_QA

#1060 Remove VM confirmation - update title and warning message
  src/components/VmActions/index.js
  src/intl/messages.js
Labels: Flag: Needs QE, Status: ON_QA

#1118 Fixed Windows VM creation bug
  src/actions/index.js
  src/components/VmDetails/cards/DetailsCard/CloudInit/SysprepForm.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDialog/index.js
  src/components/utils/timezones.json
  src/constants/index.js
  src/ovirtapi/transform.js
  src/reducers/config.js
  src/sagas/server-configs.js
Labels: Flag: Needs QE, Status: ON_QA

#1108 Added 404 handler
  packaging/ovirt-web-ui.war/WEB-INF/web.xml
  src/GlobalErrorBoundary.js
  src/Handler404.js
  src/components/ErrorContent/index.js
  src/components/ErrorContent/style.css
  src/components/PageRouter.js
  src/components/Pages/index.js
  src/constants/pages.js
  src/error.css
  src/intl/messages.js
  src/reducers/vms.js
  src/routes.js
  src/sagas/index.js
Labels: Status: ON_QA
