Repository oVirt/ovirt-web-ui, pull requests merged in 2020-10, with the labels that each got.

#1300 CreateVmWizard Networking step - Fix saving new nic error
  src/components/CreateVmWizard/steps/Networking.js
Labels: Status: ON_QA

#1228 Create VM, Network - create vnic with empty vnicProfile
  src/components/CreateVmWizard/CreateVmWizard.js
  src/components/CreateVmWizard/steps/Networking.js
  src/components/CreateVmWizard/steps/SummaryReview.js
  src/components/VmDetails/cards/NicsCard/NicEditor.js
  src/components/utils/build-select-box-lists.js
  src/constants/pages.js
  src/intl/messages.js
  src/intl/translated-messages.json
Labels: Status: ON_QA

#1303 Update minimum ovirt version to 4.4
  src/version.js.in
Labels: Type: Developers only, Type: Enhancement

#1304 Shorten the recomendedValuesForThreads message for the Threads tooltip
  src/components/VmDetails/cards/DetailsCard/index.js
  src/intl/messages.js
  src/intl/translated-messages.json
Labels: hacktoberfest-accepted

#1266 Create VM Wizard - add indicators to missing/invalid fields on BasicSettings step
  src/components/CreateVmWizard/steps/BasicSettings.js
  src/components/SelectBox.js
  src/components/sharedStyle.css
Labels: Status: ON_QA

#1310 CreateVmWizard: Fix error in Review step and set timezone in the Basic settings correctly
  src/components/CreateVmWizard/steps/BasicSettings.js
Labels: hacktoberfest-accepted

#1305 Update Zanata tools to use the maven plugin
  scripts/intl/intl-zanata-pull.sh
  scripts/intl/intl-zanata-push.sh
Labels: Type: Developers only

#1309 VM filter - Makes the filter be case insensitive
  src/utils/vms-filters.js
Labels: Status: ON_QA

#1315 Make the PF delete icon in the VM details red
  src/index-nomodules.css
Labels: hacktoberfest-accepted
