Repository oVirt/ovirt-web-ui, pull requests merged in 2020-11, with the labels that each got.

#1301 TableInlineEditRow - set button position using row position and fixed row height
  src/components/CreateVmWizard/steps/_TableInlineEditRow.js
Labels: Status: ON_QA

#1288 Display proper sysprep timezone default value in CreateVmWizard and VM Details card
  src/components/CreateVmWizard/steps/BasicSettings.js
  src/components/SelectBox.js
  src/components/VmDetails/cards/DetailsCard/CloudInit/SysprepForm.js
  src/components/VmDetails/cards/DetailsCard/CloudInit/index.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/intl/messages.js
Labels: Status: ON_QA

#1314 Make the VM console file for SPICE downloaded with proper name and vv.extension
  src/helpers.js
Labels: Status: ON_QA, hacktoberfest-accepted

#1289 Tooltip refactoring - use one type of tooltip to create consistency in VM portal
  src/components/CreateVmWizard/steps/BasicSettings.js
  src/components/CreateVmWizard/steps/Networking.js
  src/components/CreateVmWizard/steps/Storage.js
  src/components/CreateVmWizard/steps/SummaryReview.js
  src/components/CreateVmWizard/steps/style.css
  src/components/OverlayTooltip/index.js
  src/components/SelectBox.js
  src/components/Toolbar/VmSort.js
  src/components/VmActions/index.js
  src/components/VmDetails/BaseCard.js
  src/components/VmDetails/CardEditButton.js
  src/components/VmDetails/cards/DetailsCard/FieldRow.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DetailsCard/style.css
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/components/VmDetails/cards/DisksCard/DiskListItem.js
  src/components/VmDetails/cards/DisksCard/DiskStateIcon.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/NicsCard/NicEditor.js
  src/components/VmDetails/cards/NicsCard/NicLinkStateIcon.js
  src/components/VmDetails/cards/NicsCard/NicListItem.js
  src/components/VmDetails/cards/NicsCard/index.js
  src/components/VmDetails/cards/OverviewCard/index.js
  src/components/VmDetails/cards/SnapshotsCard/SnapshotItem.js
  src/components/VmDetails/cards/UtilizationCard/CpuCharts.js
  src/components/VmDetails/cards/UtilizationCard/DiskCharts.js
  src/components/VmDetails/cards/UtilizationCard/MemoryCharts.js
  src/components/VmDetails/cards/UtilizationCard/NetworkingCharts.js
  src/components/VmStatusIcon/index.js
  src/components/VmUserMessages/Bellicon.js
  src/components/VmsList/BaseCard.js
  src/components/VmsList/Pool.js
  src/components/VmsList/Vm.js
  src/components/VmsPageHeader/UserMenu.js
  src/components/VmsPageHeader/index.js
  src/components/tooltips/InfoTooltip.js
  src/components/tooltips/Tooltip.js
  src/components/tooltips/index.js
  src/components/tooltips/style.css
  src/intl/messages.js
  src/intl/translated-messages.json
Labels: Status: ON_QA

#1324 Add 'yarn intl:check-use' script
  package.json
  scripts/intl/check-message-use.sh
Labels: Type: Developers only

#1325 Add linting rules for React hooks
  config/eslint.js
  package.json
  src/components/VmsList/VmCardList.js
  yarn.lock
Labels: Type: Developers only

#1333 Fix tooltip propType errors
  src/components/VmDetails/BaseCard.js
  src/components/VmDetails/CardEditButton.js
  src/components/VmDetails/cards/DetailsCard/FieldRow.js
Labels: Type: Developers only

#1318 Filter the clusters with no architecture and cpu-type attached - CreateVmWizard and Details card
  src/components/CreateVmWizard/steps/BasicSettings.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/utils/build-select-box-lists.js
  src/intl/messages.js
  src/ovirtapi/transform.js
Labels: Status: ON_QA

#1265 Create VM - BasicSettings, select automatically single option menu
  src/components/CreateVmWizard/CreateVmWizard.js
  src/components/CreateVmWizard/helpers.js
  src/components/CreateVmWizard/steps/BasicSettings.js
Labels: Status: ON_QA
