Repository oVirt/ovirt-web-ui, pull requests merged in 2020-06, with the labels that each got.

#1236 Enable Shutdown button for a suspended VM
  src/vm-status.js
Labels: Status: ON_QA

#1217 added explicitly width value to disk size FormControl field
  src/components/CreateVmWizard/steps/Storage.js
  src/components/CreateVmWizard/steps/style.css
Labels: Flag: Needs QE, Status: ON_QA

#1213 Create VM Wizard - add to the "T" badge a tooltip to explain device source
  src/components/CreateVmWizard/steps/Networking.js
  src/components/CreateVmWizard/steps/Storage.js
  src/intl/messages.js
Labels: Flag: Needs QE, Flag: Needs UI review, Status: ON_QA

#1203 Create VM Wizard - reset basic settings fields back to baseline defaults when changing "Provision Source" field value
  src/components/CreateVmWizard/CreateVmWizard.js
  src/components/CreateVmWizard/steps/BasicSettings.js
Labels: Flag: Needs QE, Status: ON_QA

#1225 Update UPDATE_VMS reducer to handle `copySubResources` properly
  src/reducers/vms.js
  src/sagas/index.js
Labels: Flag: Needs QE, Status: ON_QA

#1200 Increase parallel calls during login data fetch
  src/sagas/login.js
  src/sagas/server-configs.js
Labels: Flag: Needs QE, Status: ON_QA

#1238 Update fetch page size, refactor background refresh sagas
  src/config.js
  src/reducers/vms.js
  src/sagas/background-refresh.js
  src/sagas/index.js
  src/sagas/login.js
Labels: Flag: Needs QE, Status: ON_QA
