Repository oVirt/ovirt-web-ui, pull requests merged in 2020-08, with the labels that each got.

#1241 Improve Vm Card List pagination and infinite scroll
  package.json
  src/actions/index.js
  src/actions/pool.js
  src/actions/vm.js
  src/components/CreateVmWizard/AddVmButton.js
  src/components/Pages/index.js
  src/components/VmDetails/cards/OverviewCard/index.js
  src/components/VmStatusIcon/index.js
  src/components/VmsList/BaseCard.js
  src/components/VmsList/Pool.js
  src/components/VmsList/Vm.js
  src/components/VmsList/VmCardList.js
  src/components/VmsList/Vms.js
  src/components/VmsList/index.js
  src/components/VmsList/style.css
  src/components/VmsPageHeader/index.js
  src/constants/index.js
  src/constants/pages.js
  src/mock/ovirtapi.mock.js
  src/ovirtapi/index.js
  src/reducers/vms.js
  src/routes.js
  src/sagas/background-refresh.js
  src/sagas/index.js
  yarn.lock
Labels: Status: ON_QA

#1226 Remove Components that are no longer used
  Makefile.am
  config/babel.dev.js
  config/babel.prod.js
  src/components/CloudInitEditor/index.js
  src/components/CloudInitEditor/style.css
  src/components/Confirmation/Popover.js
  src/components/ConsoleOptions/index.js
  src/components/ConsoleOptions/style.css
  src/components/DetailContainer.js
  src/components/HostConsole/index.js
  src/components/HostConsole/style.css
  src/components/IconUpload/index.js
  src/components/IconUpload/style.css
  src/components/NewDiskDialog/index.js
  src/components/NewDiskDialog/style.css
  src/components/VmDetailRow/ExpandableList.js
  src/components/VmDetailRow/index.js
  src/components/VmDetailRow/style.css
  src/components/VmDetails/cards/DetailsCard/CloudInit/index.js
  src/components/VmDetails/cards/DetailsCard/index.js
  src/components/VmDetails/cards/DisksCard/index.js
  src/components/VmDetails/cards/SnapshotsCard/SnapshotDetail.js
  src/components/VmDialog/index.js
  src/components/VmDialog/style.css
  src/components/VmDisks/VmDisk.js
  src/components/VmDisks/index.js
  src/components/VmDisks/style.css
  src/components/VmNics/NewNicModal.js
  src/components/VmNics/index.js
  src/components/VmNics/style.css
  src/components/sharedStyle.css
  src/components/utils/disks.js
  src/components/utils/disks.test.js
  src/components/utils/index.js
Labels: Type: Developers only

#1239 Create VM - add close confirmation to the wizard
  src/components/CreateVmWizard/CreateVmWizard.js
Labels: Status: ON_QA

#1218 Fix DiskImageEditor default format and size tooltip
  src/components/CreateVmWizard/CreateVmWizard.js
  src/components/CreateVmWizard/steps/Storage.js
  src/components/CreateVmWizard/steps/SummaryReview.js
  src/components/VmDetails/cards/DisksCard/DiskImageEditor.js
  src/components/utils/build-select-box-lists.js
  src/intl/messages.js
  src/intl/translated-messages.json
  src/sagas/vmChanges.js
Labels: Status: ON_QA

#1235 Set usb-filter and enable-usb-autoshare entries in console.vv properly
  src/actions/console.js
  src/actions/index.js
  src/components/VmActions/ConsoleConfirmationModal.js
  src/constants/index.js
  src/reducers/config.js
  src/sagas/console/index.js
  src/sagas/console/vvFileUtils.js
  src/sagas/server-configs.js
Labels: Status: ON_QA

#1243 Allow opening console.vv in virt-viewer when clicking on VM console in Firefox
  src/helpers.js
Labels: Status: ON_QA

#1229 Create VM Wizard - added tooltip message to Disk size field on edit mode
  src/components/CreateVmWizard/steps/Storage.js
Labels: Status: ON_QA

#1268 Fix create vm storage step moving bootable flag regression
  src/components/CreateVmWizard/steps/Storage.js
Labels: Status: ON_QA

#1271 Display Pool entities containing search term when filtering
  src/components/VmsList/VmCardList.js
Labels: Status: ON_QA

#1263 CreateVMWizard - adjusting row's spacers to create consistency between edit and create modes
  src/components/CreateVmWizard/steps/Networking.js
  src/components/CreateVmWizard/steps/Storage.js
  src/components/CreateVmWizard/steps/style.css
Labels: Flag: Needs QE, Status: ON_QA

#1220 Make VM time zone format compatible with the VM OS when creating a VM, display time zone in the Review report step
  src/components/CreateVmWizard/steps/BasicSettings.js
  src/components/CreateVmWizard/steps/SummaryReview.js
  src/sagas/vmChanges.js
Labels: Status: ON_QA

#1262 Display proper VM CPU Load considering the number of vCPUs
  src/components/VmDetails/cards/UtilizationCard/CpuCharts.js
  src/components/VmDetails/cards/UtilizationCard/index.js
Labels: Status: ON_QA
